# Generated by Django 3.2.3 on 2021-06-22 23:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='uuid')),
                ('name', models.CharField(max_length=30, verbose_name='name')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='profile_labels', to='categories.label', verbose_name='label')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='profile_labels', to='profiles.profile', verbose_name='profile')),
            ],
            options={
                'verbose_name': 'profile label',
                'verbose_name_plural': 'profile labels',
            },
        ),
        migrations.CreateModel(
            name='ProfileCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='uuid')),
                ('name', models.CharField(max_length=30, verbose_name='name')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='profile_categories', to='categories.category', verbose_name='category')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='profile_categories', to='profiles.profile', verbose_name='profile')),
            ],
            options={
                'verbose_name': 'profile category',
                'verbose_name_plural': 'profile categories',
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='categories', through='profiles.ProfileCategory', to='categories.Category'),
        ),
        migrations.AddField(
            model_name='profile',
            name='labels',
            field=models.ManyToManyField(blank=True, related_name='labels', through='profiles.ProfileLabel', to='categories.Label'),
        ),
    ]
