# Generated by Django 3.2.3 on 2021-06-23 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20210622_1854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilecategory',
            name='name',
        ),
        migrations.RemoveField(
            model_name='profilelabel',
            name='name',
        ),
    ]
