# Generated by Django 3.2.3 on 2021-06-07 14:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('countries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='uuid')),
                ('name', models.CharField(max_length=30, verbose_name='name')),
                ('code', models.CharField(max_length=3, unique=True, verbose_name='code')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='entities', to='countries.country', verbose_name='country')),
            ],
            options={
                'verbose_name': 'entity',
                'verbose_name_plural': 'entities',
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='uuid')),
                ('name', models.CharField(max_length=30, verbose_name='name')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='wallets', to='countries.currency', verbose_name='currency')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='wallets', to='wallets.entity', verbose_name='entity')),
            ],
            options={
                'verbose_name': 'entity',
                'verbose_name_plural': 'entities',
            },
        ),
    ]
