# Generated by Django 3.2.3 on 2021-05-30 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False, verbose_name='code')),
                ('name', models.CharField(max_length=15, verbose_name='name')),
                ('english_name', models.CharField(max_length=60, verbose_name='english name')),
                ('symbol', models.CharField(max_length=3, verbose_name='symbol')),
            ],
            options={
                'verbose_name': 'currency',
                'verbose_name_plural': 'currencies',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('code', models.CharField(max_length=2, primary_key=True, serialize=False, verbose_name='code')),
                ('name', models.CharField(max_length=60, verbose_name='name')),
                ('english_name', models.CharField(max_length=60, verbose_name='english name')),
                ('flag_url', models.URLField(blank=True, default='', max_length=3, verbose_name='flag url')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='countries', to='countries.currency', verbose_name='currency')),
            ],
            options={
                'verbose_name': 'country',
                'verbose_name_plural': 'countries',
            },
        ),
    ]
